# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, verbose_name='\u6d3b\u52a8\u7c7b\u578b\u540d\u79f0')),
                ('department_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.IntegerField(verbose_name='\u521b\u5efa\u4eba')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='desc',
        ),
        migrations.AddField(
            model_name='user',
            name='describition',
            field=models.TextField(blank=True, null=True, verbose_name='\u63cf\u8ff0\u8bf4\u660e\uff08\u975e\u5fc5\u987b\uff09'),
        ),
    ]
