# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': '\u90e8\u95e8'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name_plural': '\u804c\u4f4d'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '\u7528\u6237'},
        ),
    ]
