# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170608_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('view_department', '\u53ef\u4ee5\u67e5\u770b\u90e8\u95e8'),), 'verbose_name_plural': '\u90e8\u95e8'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'permissions': (('view_position', '\u901a\u7528\uff1a\u53ef\u4ee5\u67e5\u770b\u804c\u4f4d'),), 'verbose_name_plural': '\u804c\u4f4d'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_chinesename', '\u901a\u7528\uff1a\u67e5\u770b\u7528\u6237\u4e2d\u6587\u540d'),), 'verbose_name': 'user', 'verbose_name_plural': '\u7528\u6237'},
        ),
    ]
