# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170522_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='\u6d3b\u52a8\u7c7b\u578b\u540d\u79f0')),
                ('position_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('view_department', '\u53ef\u4ee5\u67e5\u770b\u90e8\u95e8'),)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
 

    ]
