# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170608_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'permissions': (('view_department', '\u901a\u7528\uff1a\u53ef\u4ee5\u67e5\u770b\u90e8\u95e8'),), 'verbose_name_plural': '\u90e8\u95e8'},
        ),
    ]
