# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170509_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u90e8\u95e8id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u804c\u4f4did'),
        ),
    ]
