# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20170524_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_chinesename', '\u67e5\u770b\u4e2d\u6587\u7528\u6237'),)},
        ),
    ]
