# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20170525_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_chinesename', '\u81ea\u5b9a\u4e49\uff1a\u67e5\u770b\u4e2d\u6587\u7528\u6237'),)},
        ),
    ]
