# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170525_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position_name',
            field=models.CharField(max_length=100, verbose_name='\u804c\u4f4d\u540d\u79f0'),
        ),
    ]
