# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 00:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u4e8b\u4ef6\u63cf\u8ff0')),
                ('event_date', models.DateField(verbose_name='\u4e8b\u4ef6\u65e5\u671f')),
                ('start_time', models.TimeField(verbose_name='\u4e8b\u4ef6\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.TimeField(verbose_name='\u4e8b\u4ef6\u7ed3\u675f\u65f6\u95f4')),
                ('fin_percentage', models.IntegerField(default=0, verbose_name='\u5b8c\u6210\u767e\u5206\u6bd4')),
                ('up_reporter_id', models.CharField(max_length=64, verbose_name='\u4e0a\u6e38\u6c47\u62a5\u4eba')),
                ('down_reporter_ids', models.CharField(max_length=64, verbose_name='\u4e0b\u6e38\u6c47\u62a5\u4eba')),
                ('dev_event_remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('dev_event_create_time', models.DateTimeField(auto_now_add=True)),
                ('dev_event_owner_id', models.IntegerField(null=True, verbose_name='\u4e8b\u4ef6\u6240\u5c5e\u4eba')),
                ('dev_event_project_id', models.IntegerField(null=True, verbose_name='\u6240\u5c5e\u9879\u76ee')),
                ('dev_event_type_id', models.IntegerField(null=True, verbose_name='\u4e8b\u4ef6\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='DevEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_name', models.CharField(max_length=100, verbose_name='\u4e8b\u4ef6\u7c7b\u578b\u540d\u79f0')),
                ('dev_event_type_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('status', models.CharField(max_length=64, verbose_name='\u9879\u76ee\u72b6\u6001\uff1a00\uff0c\u5173\u95ed\uff1b01\uff0c\u542f\u52a8')),
                ('dev_project_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='SaleActiveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_type_name', models.CharField(max_length=100, verbose_name='\u6d3b\u52a8\u7c7b\u578b\u540d\u79f0')),
                ('sale_active_type_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='\u5ba2\u6237\u5168\u79f0')),
                ('short_name', models.CharField(max_length=100, verbose_name='\u5ba2\u6237\u7b80\u79f0')),
                ('contact_post', models.CharField(max_length=100, verbose_name='\u4e3b\u8981\u8054\u7cfb\u4eba\u804c\u4f4d')),
                ('contact_name', models.CharField(max_length=100, verbose_name='\u4e3b\u8981\u8054\u7cfb\u4eba\u59d3\u540d')),
                ('contact_mdn', models.CharField(max_length=100, verbose_name='\u4e3b\u8981\u8054\u7cfb\u4eba\u624b\u673a\u53f7\u7801')),
                ('contact_tel_num', models.CharField(max_length=100, verbose_name='\u4e3b\u8981\u8054\u7cfb\u4eba\u7535\u8bdd\u53f7\u7801')),
                ('sale_customer_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5ba2\u6237\u5907\u6ce8')),
                ('sale_customer_owner_id', models.IntegerField(verbose_name='\u5ba2\u6237\u6dfb\u52a0\u4eba')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_con_post', models.CharField(max_length=500, verbose_name='\u5ba2\u6237\u804c\u4f4d')),
                ('visit_date', models.DateField(verbose_name='\u62dc\u8bbf\u65f6\u95f4')),
                ('cus_con_mdn', models.CharField(default=None, max_length=64, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('cus_con_tel_num', models.CharField(max_length=64, verbose_name='\u5ba2\u6237\u8054\u7cfb\u65b9\u5f0f')),
                ('cus_con_wechart', models.CharField(max_length=64, verbose_name='\u5ba2\u6237\u7684\u5fae\u4fe1\u53f7')),
                ('communicate_record', models.CharField(max_length=500, verbose_name='\u6c9f\u901a\u6210\u679c')),
                ('sale_event_remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('sale_event_owner_id', models.IntegerField(null=True, verbose_name='\u62dc\u8bbf\u4eba')),
                ('active_type_id', models.IntegerField(null=True, verbose_name='\u62dc\u8bbf\u7c7b\u578b')),
                ('sale_customer_id', models.IntegerField(null=True, verbose_name='\u5ba2\u6237ID')),
                ('sale_phase_id', models.IntegerField(null=True, verbose_name='\u62dc\u8bbf\u9636\u6bb5')),
            ],
        ),
        migrations.CreateModel(
            name='SalePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=64, verbose_name='\u9636\u6bb5\u540d\u79f0\uff0c\u4f8b\u5982B,C,D,E,F,G')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='\u9636\u6bb5\u63cf\u8ff0')),
                ('phase_count', models.IntegerField(verbose_name='\u6700\u5927\u62dc\u8bbf\u6b21\u6570')),
                ('sale_phase_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('target', models.CharField(max_length=500, verbose_name='\u76ee\u6807\uff0cjson\u5b58\u50a8')),
                ('phase_count', models.IntegerField(verbose_name='\u6700\u5927\u62dc\u8bbf\u6b21\u6570')),
                ('sale_target_remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u9500\u552e\u76ee\u6807\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('sale_target_owner_id', models.IntegerField(verbose_name='\u76ee\u6807\u6240\u5c5e\u4eba')),
            ],
        ),
        migrations.CreateModel(
            name='WeekSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('summary', models.CharField(max_length=500, verbose_name='\u603b\u7ed3')),
                ('self_evaluation', models.CharField(max_length=500, verbose_name='\u81ea\u6211\u8bc4\u4ef7')),
                ('plan', models.CharField(max_length=500, verbose_name='\u8ba1\u5212')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('summary_owner_id', models.IntegerField(verbose_name='\u4e8b\u4ef6\u6240\u5c5e\u4eba')),
            ],
        ),
    ]
