# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='\u4e8b\u4ef6\u63cf\u8ff0')),
                ('start_time', models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('fin_percentage', models.IntegerField(default=0, verbose_name='\u5b8c\u6210\u767e\u5206\u6bd4')),
                ('up_reporter_id', models.CharField(max_length=64, verbose_name='\u4e0a\u6e38\u6c47\u62a5\u4eba')),
                ('down_reporter_ids', models.CharField(max_length=64, verbose_name='\u4e0b\u6e38\u6c47\u62a5\u4eba')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevEventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='\u4e8b\u4ef6\u7c7b\u578b\u540d\u79f0')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='DevProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('creater_id', models.IntegerField(verbose_name='\u521b\u5efa\u4eba')),
                ('status', models.CharField(max_length=64, verbose_name='\u9879\u76ee\u72b6\u6001\uff1a00\uff0c\u5173\u95ed\uff1b01\uff0c\u542f\u52a8')),
                ('remark', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5907\u6ce8')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('summary', models.CharField(max_length=500, verbose_name='\u603b\u7ed3')),
                ('self_evaluation', models.CharField(max_length=500, verbose_name='\u603b\u7ed3')),
                ('plan', models.CharField(max_length=500, verbose_name='\u603b\u7ed3')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e8b\u4ef6\u6240\u5c5e\u4eba')),
            ],
        ),
        migrations.AddField(
            model_name='devevent',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DevEventType', verbose_name='\u4e8b\u4ef6\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='devevent',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e8b\u4ef6\u6240\u5c5e\u4eba'),
        ),
        migrations.AddField(
            model_name='devevent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DevProject', verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
