# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=1024)),
                ('hided', models.BooleanField(default=0, verbose_name='\u662f\u5426\u9690\u85cf')),
            ],
        ),
    ]
