# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-06 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deveventtype',
            options={'verbose_name': '\u4e8b\u4ef6\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='devproject',
            options={'verbose_name': '\u9879\u76ee'},
        ),
        migrations.AlterModelOptions(
            name='saleactivetype',
            options={'verbose_name': '\u6d3b\u52a8\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='salephase',
            options={'verbose_name': '\u9500\u552e\u9636\u6bb5'},
        ),
        migrations.AlterModelOptions(
            name='saletarget',
            options={'verbose_name': '\u9500\u552e\u76ee\u6807'},
        ),
    ]
