# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontent',
            name='complete_status',
            field=models.IntegerField(default=0, verbose_name='\u5b8c\u6210\u72b6\u6001'),
        ),
        migrations.AddField(
            model_name='jobcontent',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='jobcontent',
            name='job_manager',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5de5\u4f5c\u8d1f\u8d23\u4eba'),
        ),
        migrations.AddField(
            model_name='jobcontent',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='jobcontent',
            name='work_auditor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5de5\u4f5c\u5ba1\u6838\u4eba'),
        ),
    ]
