# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devproject',
            old_name='creater_id',
            new_name='creator_id',
        ),
        migrations.AddField(
            model_name='deveventtype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deveventtype',
            name='creator_id',
            field=models.IntegerField(default=1, verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
    ]
