# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170427_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontent',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8'),
        ),
    ]
