# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170531_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletarget',
            name='phase_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SalePhase', verbose_name='\u9636\u6bb5\u540d\u79f0\uff0c\u4f8b\u5982B,C,D,E,F,G'),
        ),
    ]
