# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170606_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devevent',
            options={'verbose_name_plural': '\u5468\u62a5\u4e8b\u4ef6'},
        ),
        migrations.AlterModelOptions(
            name='deveventtype',
            options={'verbose_name_plural': '\u4e8b\u4ef6\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='devproject',
            options={'verbose_name_plural': '\u9879\u76ee'},
        ),
        migrations.AlterModelOptions(
            name='saleactivetype',
            options={'verbose_name_plural': '\u6d3b\u52a8\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='salecustomer',
            options={'verbose_name_plural': '\u5ba2\u6237\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='saleevent',
            options={'verbose_name_plural': '\u9500\u552e\u4e8b\u4ef6'},
        ),
        migrations.AlterModelOptions(
            name='salephase',
            options={'verbose_name_plural': '\u9500\u552e\u9636\u6bb5'},
        ),
        migrations.AlterModelOptions(
            name='saletarget',
            options={'verbose_name_plural': '\u9500\u552e\u76ee\u6807'},
        ),
        migrations.AlterModelOptions(
            name='weeksummary',
            options={'verbose_name_plural': '\u5468\u62a5\u603b\u7ed3'},
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='cus_con_tel_num',
            field=models.CharField(max_length=64, verbose_name='\u5ba2\u6237\u7535\u8bdd\u53f7\u7801'),
        ),
    ]
