# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170509_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devevent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='devevent',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='devevent',
            name='project',
        ),
        migrations.AddField(
            model_name='devevent',
            name='event_type_id',
            field=models.IntegerField(default=None, verbose_name='\u4e8b\u4ef6\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='devevent',
            name='owner_id',
            field=models.IntegerField(default=None, verbose_name='\u4e8b\u4ef6\u6240\u5c5e\u4eba'),
        ),
        migrations.AddField(
            model_name='devevent',
            name='project_id',
            field=models.IntegerField(default=None, verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
