# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170613_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='devevent',
            name='duration_time',
            field=models.FloatField(default=0, verbose_name='\u5de5\u4f5c\u65f6\u957f'),
            preserve_default=False,
        ),
    ]
