# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170601_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletarget',
            name='phase_name',
            field=models.CharField(max_length=64, verbose_name='\u9636\u6bb5\u540d\u79f0\uff0c\u4f8b\u5982B,C,D,E,F,G'),
        ),
    ]
