# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-16 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170516_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeksummary',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='weeksummary',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
