# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170608_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deveventtype',
            options={'permissions': (('view_deveventtype', '\u6280\u672f\u5458\u5de5\uff1a\u67e5\u770b\u4e8b\u4ef6\u7c7b\u578b'),)},
        ),
        migrations.AlterModelOptions(
            name='devproject',
            options={'permissions': (('view_devproject', '\u6280\u672f\u5458\u5de5\uff1a\u67e5\u770b\u9879\u76ee\u540d\u79f0'),)},
        ),
    ]
