# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobcontent_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcontent',
            name='operator',
            field=models.CharField(default='admin', max_length=10),
        ),
    ]
