# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170509_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devevent',
            name='event_type_id',
            field=models.IntegerField(default=None, null=True, verbose_name='\u4e8b\u4ef6\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='devevent',
            name='project_id',
            field=models.IntegerField(default=None, null=True, verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
