# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170608_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devevent',
            options={'permissions': (('view_devevent', '\u6280\u672f\u5458\u5de5\uff1a\u67e5\u770b\u672c\u4eba\u7684\u4e8b\u4ef6'), ('export_excel', '\u5bfc\u51fa\u672c\u4eba\u7684\u4e8b\u4ef6\u4e3aexcel'), ('analysis_devevent', '\u6280\u672f\u4e3b\u7ba1\uff1a\u5206\u6790\u5468\u62a5\u4e8b\u4ef6')), 'verbose_name_plural': '\u5468\u62a5\u4e8b\u4ef6'},
        ),
    ]
