# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170516_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeksummary',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='weeksummary',
            name='start_date',
            field=models.DateField(verbose_name='\u8d77\u59cb\u65e5\u671f'),
        ),
    ]
