# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170509_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
