# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170608_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeksummary',
            options={'permissions': (('view_weeksummary', '\u6240\u6709\u5458\u5de5:\u67e5\u770b\u5458\u5de5\u81ea\u5df1\u7684\u5468\u62a5\u603b\u7ed3'), ('insert_weeksummary', '\u6240\u6709\u5458\u5de5:\u65b0\u589e\u81ea\u5df1\u7684\u5468\u62a5\u603b\u7ed3'), ('analysis_weekly_summary', '\u6240\u6709\u4e3b\u7ba1:\u67e5\u770b\u5458\u5de5\u6bcf\u5468\u5468\u62a5\u603b\u7ed3')), 'verbose_name_plural': '\u5468\u62a5\u603b\u7ed3'},
        ),
    ]
