# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170509_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devevent',
            name='owner_id',
            field=models.IntegerField(null=True, verbose_name='\u4e8b\u4ef6\u6240\u5c5e\u4eba'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='active_type',
            field=models.IntegerField(null=True, verbose_name='\u62dc\u8bbf\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='owner',
            field=models.IntegerField(null=True, verbose_name='\u62dc\u8bbf\u4eba'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='sale_customer',
            field=models.IntegerField(null=True, verbose_name='\u5ba2\u6237ID'),
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='sale_phase',
            field=models.IntegerField(null=True, verbose_name='\u62dc\u8bbf\u9636\u6bb5'),
        ),
    ]
