# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170510_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleevent',
            old_name='active_type',
            new_name='active_type_id',
        ),
        migrations.RenameField(
            model_name='saleevent',
            old_name='owner',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='saleevent',
            old_name='sale_customer',
            new_name='sale_customer_id',
        ),
        migrations.RenameField(
            model_name='saleevent',
            old_name='sale_phase',
            new_name='sale_phase_id',
        ),
    ]
