# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_deveventtype_deveventtype_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeksummary',
            name='start_date',
        ),
        migrations.AddField(
            model_name='weeksummary',
            name='natural_week',
            field=models.CharField(default='2017-20', max_length=64, verbose_name='\u81ea\u7136\u5468'),
            preserve_default=False,
        ),
    ]
