# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170608_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleactivetype',
            options={'permissions': (('view_SaleActivateType', '\u9500\u552e\u5458\u5de5:\u67e5\u770b\u9500\u552e\u6d3b\u52a8\u7c7b\u578b'),), 'verbose_name_plural': '\u6d3b\u52a8\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='salecustomer',
            options={'permissions': (('view_SaleCustomer', '\u9500\u552e\u5458\u5de5:\u67e5\u770b\u9500\u552e\u5ba2\u6237'),), 'verbose_name_plural': '\u5ba2\u6237\u4fe1\u606f'},
        ),
    ]
