# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170518_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeksummary',
            name='natural_week',
            field=models.CharField(max_length=64, unique=True, verbose_name='\u81ea\u7136\u5468'),
        ),
    ]
