# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170510_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleevent',
            old_name='owner_id',
            new_name='sale_event_owner_id',
        ),
        migrations.RemoveField(
            model_name='saleactivetype',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='saletarget',
            name='owner',
        ),
        migrations.AddField(
            model_name='saletarget',
            name='sale_target_owner_id',
            field=models.IntegerField(default=1, verbose_name='\u76ee\u6807\u6240\u5c5e\u4eba'),
            preserve_default=False,
        ),
    ]
