# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170608_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleevent',
            options={'permissions': (('view_saleevent', '\u9500\u552e\u5458\u5de5:\u67e5\u770b\u9500\u552e\u62dc\u8bbf\u4e8b\u4ef6'), ('analysis_sale_event', '\u9500\u552e\u4e3b\u7ba1:\u5206\u6790\u9500\u552e\u62dc\u8bbf\u4e8b\u4ef6'), ('display_sale_event', '\u9500\u552e\u4e3b\u7ba1:\u67e5\u8be2\u9500\u552e\u62dc\u8bbf\u4e8b\u4ef6')), 'verbose_name_plural': '\u9500\u552e\u4e8b\u4ef6'},
        ),
        migrations.AlterModelOptions(
            name='salephase',
            options={'permissions': (('view_SalePhase', '\u9500\u552e\u5458\u5de5:\u67e5\u770b\u9500\u552e\u9636\u6bb5'),), 'verbose_name_plural': '\u9500\u552e\u9636\u6bb5'},
        ),
    ]
