# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170519_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saletarget',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='saletarget',
            name='start_time',
        ),
        migrations.AddField(
            model_name='saletarget',
            name='natural_week',
            field=models.CharField(default='2017-20', max_length=64, verbose_name='\u81ea\u7136\u5468'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saletarget',
            name='phase_name',
            field=models.CharField(default='A', max_length=64, verbose_name='\u9636\u6bb5\u540d\u79f0\uff0c\u4f8b\u5982B,C,D,E,F,G'),
            preserve_default=False,
        ),
    ]
