# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170522_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletarget',
            name='target',
            field=models.IntegerField(verbose_name='\u76ee\u6807'),
        ),
    ]
