# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-10 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170510_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devevent',
            old_name='create_time',
            new_name='dev_event_create_time',
        ),
    ]
