# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-24 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170522_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devevent',
            options={'permissions': (('export_excel', '\u5bfc\u51fa\u672c\u4eba\u7684\u4e8b\u4ef6\u4e3aexcel'),)},
        ),
    ]
