# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170608_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deveventtype',
            options={'permissions': (('view_deveventtype', '\u6280\u672f\u5458\u5de5\uff1a\u67e5\u770b\u4e8b\u4ef6\u7c7b\u578b'),), 'verbose_name_plural': '\u4e8b\u4ef6\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='devproject',
            options={'permissions': (('view_devproject', '\u6280\u672f\u5458\u5de5\uff1a\u67e5\u770b\u9879\u76ee\u540d\u79f0'),), 'verbose_name_plural': '\u9879\u76ee'},
        ),
        migrations.AlterField(
            model_name='saletarget',
            name='natural_week',
            field=models.CharField(max_length=64, verbose_name='\u81ea\u7136\u5468,\u5982 2017-10 '),
        ),
        migrations.AlterField(
            model_name='saletarget',
            name='phase_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SalePhase', verbose_name='\u9636\u6bb5\u540d\u79f0'),
        ),
    ]
