# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170510_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeksummary',
            old_name='owner',
            new_name='summary_owner_id',
        ),
    ]
