# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170608_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devevent',
            options={'permissions': (('view_devevent', '\u6280\u672f\u5458\u5de5\uff1a\u67e5\u770b\u672c\u4eba\u7684\u4e8b\u4ef6'), ('insert_devevent', '\u6280\u672f\u5458\u5de5\uff1a\u65b0\u589e\u5de5\u4f5c\u4e8b\u4ef6'), ('export_excel', '\u6280\u672f\u5458\u5de5\uff1a\u5bfc\u51fa\u672c\u4eba\u7684\u4e8b\u4ef6\u4e3aexcel'), ('analysis_devevent', '\u6280\u672f\u4e3b\u7ba1\uff1a\u5206\u6790\u5468\u62a5\u4e8b\u4ef6'), ('markDel_devevent', '\u6280\u672f\u5458\u5de5:\u6807\u8bb0\u5220\u9664\u81ea\u5df1\u7684\u5de5\u4f5c\u4e8b\u4ef6')), 'verbose_name_plural': '\u5468\u62a5\u4e8b\u4ef6'},
        ),
    ]
