# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170609_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salecustomer',
            options={'permissions': (('view_SaleCustomer', '\u9500\u552e\u5458\u5de5:\u67e5\u770b\u9500\u552e\u5ba2\u6237'), ('insert_salecustomer', '\u9500\u552e\u5458\u5de5:\u589e\u52a0\u9500\u552e\u5ba2\u6237')), 'verbose_name_plural': '\u5ba2\u6237\u4fe1\u606f'},
        ),
    ]
