# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170511_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeksummary',
            name='summary_owner_id',
            field=models.IntegerField(verbose_name='\u4e8b\u4ef6\u6240\u5c5e\u4eba'),
        ),
    ]
