# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170511_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='salecustomer',
            name='sale_customer_owner_id',
            field=models.IntegerField(null=True, verbose_name='\u5ba2\u6237\u6dfb\u52a0\u4eba'),
        ),
    ]
