# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_salecustomer_sale_customer_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecustomer',
            name='sale_customer_owner_id',
            field=models.IntegerField(default=1, verbose_name='\u5ba2\u6237\u6dfb\u52a0\u4eba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='saleevent',
            name='visit_date',
            field=models.DateField(verbose_name='\u62dc\u8bbf\u65f6\u95f4'),
        ),
    ]
