# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20170525_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devevent',
            options={'permissions': (('export_excel', '\u5bfc\u51fa\u672c\u4eba\u7684\u4e8b\u4ef6\u4e3aexcel'), ('analysisi_devevent', '\u4e3b\u7ba1\uff1a\u5206\u6790\u5468\u62a5\u4e8b\u4ef6'))},
        ),
        migrations.AlterModelOptions(
            name='saleevent',
            options={'permissions': (('analysis_sale_event', '\u4e3b\u7ba1:\u5206\u6790\u9500\u552e\u62dc\u8bbf\u4e8b\u4ef6'), ('display_sale_event', '\u4e3b\u7ba1:\u67e5\u8be2\u9500\u552e\u62dc\u8bbf\u4e8b\u4ef6'))},
        ),
    ]
