# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20170525_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devevent',
            options={'permissions': (('export_excel', '\u5bfc\u51fa\u672c\u4eba\u7684\u4e8b\u4ef6\u4e3aexcel'), ('analysis_devevent', '\u4e3b\u7ba1\uff1a\u5206\u6790\u5468\u62a5\u4e8b\u4ef6'))},
        ),
    ]
