# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20170525_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleevent',
            options={'permissions': (('analysis_sale_event', '\u9500\u552e\u4e3b\u7ba1:\u5206\u6790\u9500\u552e\u62dc\u8bbf\u4e8b\u4ef6'), ('display_sale_event', '\u9500\u552e\u4e3b\u7ba1:\u67e5\u8be2\u9500\u552e\u62dc\u8bbf\u4e8b\u4ef6'))},
        ),
        migrations.AlterModelOptions(
            name='weeksummary',
            options={'permissions': (('analysis_weekly_summary', '\u6240\u6709\u4e3b\u7ba1:\u67e5\u770b\u5458\u5de5\u6bcf\u5468\u5468\u62a5\u603b\u7ed3'),)},
        ),
    ]
