# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20170525_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='devproject',
            name='enable',
            field=models.IntegerField(choices=[(0, '\u7981\u7528'), (1, '\u542f\u7528')], default=1),
        ),
    ]
