# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_devproject_enable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devproject',
            name='enable',
        ),
        migrations.AddField(
            model_name='devproject',
            name='closed_status',
            field=models.IntegerField(choices=[(0, '\u542f\u7528'), (1, '\u7981\u7528')], default=0, verbose_name='1\u4ee3\u8868\u5173\u95ed'),
        ),
        migrations.AlterField(
            model_name='devproject',
            name='project_is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
