# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20170526_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devproject',
            name='project_is_closed',
        ),
    ]
