# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-26 05:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_remove_devproject_project_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devproject',
            name='creator_id',
        ),
        migrations.AddField(
            model_name='devproject',
            name='project_creator',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u521b\u5efa\u4eba'),
            preserve_default=False,
        ),
    ]
