# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 01:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20170526_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devevent',
            name='dev_event_type_id',
        ),
        migrations.AddField(
            model_name='devevent',
            name='dev_event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.DevEventType', verbose_name='\u4e8b\u4ef6\u7c7b\u578b'),
            preserve_default=False,
        ),
    ]
