# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 01:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0028_auto_20170527_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devevent',
            name='dev_event_owner_id',
        ),
        migrations.AddField(
            model_name='devevent',
            name='dev_event_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e8b\u4ef6\u6240\u5c5e\u4eba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='devevent',
            name='dev_event_project_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u6240\u5c5e\u9879\u76ee'),
        ),
    ]
