# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-27 02:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0029_auto_20170527_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salecustomer',
            name='sale_customer_owner_id',
        ),
        migrations.RemoveField(
            model_name='saleevent',
            name='active_type_id',
        ),
        migrations.RemoveField(
            model_name='saleevent',
            name='sale_customer_id',
        ),
        migrations.RemoveField(
            model_name='saleevent',
            name='sale_event_owner_id',
        ),
        migrations.RemoveField(
            model_name='saleevent',
            name='sale_phase_id',
        ),
        migrations.RemoveField(
            model_name='weeksummary',
            name='summary_owner_id',
        ),
        migrations.AddField(
            model_name='salecustomer',
            name='sale_customer_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5ba2\u6237\u6dfb\u52a0\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleevent',
            name='active_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.SaleActiveType', verbose_name='\u62dc\u8bbf\u7c7b\u578b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleevent',
            name='sale_customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.SaleCustomer', verbose_name='\u5ba2\u6237ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleevent',
            name='sale_event_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u62dc\u8bbf\u4eba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleevent',
            name='sale_phase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.SalePhase', verbose_name='\u62dc\u8bbf\u9636\u6bb5'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeksummary',
            name='summary_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4e8b\u4ef6\u6240\u5c5e\u4eba'),
            preserve_default=False,
        ),
    ]
